### ISSUE TITLE
网络连接状态

### ISSUE THREAD

**Issue by wxlpp** [kangzubin/XMNetworking#11]
真机
6s
iOS10.1
当在didFinishLaunchingWithOptions中调用api时会直接判断网络未连接

**Comment by kangzubin** [comment]
现在网络连接状态的判断的两个方法，都是基于 `AFNetworkReachabilityManager ` 封装的。AFNetworking 的这个模块判断网络连接状态需要一段时间，你在 `-application:didFinishLaunchingWithOptions:` 方法判断网络状态可能会直接返回 `Unknown` 状态，所以建议调用 `[[XMEngine sharedEngine] networkReachability]` 时如果返回 `Unknown`（-1）时也认为网络是可连接的；事实上 `[XMCenter isNetworkReachable]` 这个方法就是这么做的，只要不是 `NotReachable`（0）都认为网络可用。
