### ISSUE TITLE
Bug?!

### ISSUE THREAD

**Issue by frankfan1990** [kangzubin/XMNetworking#12]
成功回调发生在哪个线程？tableViewCell通过自动布局自动行高，数据请求成功回调reloaddata后....crash，将reloadData手动放到主线程...妥妥的好了。

**Comment by kangzubin** [comment]
文档里写了：
> success/faillure/finished 等回调 Block 会在 XMCenter 设置的 callbackQueue 队列中被执行，如果该值为 `NULL`（默认），那么会在一个私有的并发队列（子线程）中执行回调 Block。

请您详细看文档的说明，另外，你可以通过以下方式设置回调 Block 执行的线程：

```objc
    [XMCenter setupConfig:^(XMConfig *config) {
        ...
        config.callbackQueue = dispatch_get_main_queue(); // If `NULL` (default), a private concurrent queue is used.
        ....
    }];
```
