### ISSUE TITLE
会不会设计cache？

### ISSUE THREAD

**Issue by hydyy** [kangzubin/XMNetworking#13]
如题？

**Comment by hydyy** [comment]
好的好的， 针对网络层的优化还是很有必要的哇！
我们项目目前比较稳定，但是一直在持续关注，网络层想要重构。 
看一看有没有合适的组件。

**Comment by szwq01** [comment]
加上Post/Get网络缓存开关及更新机制 ,再加上返回数据格式校验和3G/网络环境判断就完美了.之前看过你的的XMNChatBar很棒的的哦@_@.
