### ISSUE TITLE
请问， post 上传格式为data ，支持吗？

### ISSUE THREAD

**Issue by liu521227** [kangzubin/XMNetworking#14]
直接用afn3.0 代码如下：    
 
AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]];
    
    [[manager dataTaskWithRequest:request completionHandler:^(NSURLResponse * _Nonnull response, id  _Nullable responseObject, NSError * _Nullable error) {
        
        if (!error) {
            
        } else {
            NSLog(@"Error: %@, %@, %@", error, response, responseObject);
            
        }
    }] resume];

**Comment by kangzubin** [comment]
当然可以，请您详细阅读一下文档和源码中的 Upload Request 示例。
