### ISSUE TITLE
报Er'ro'r

### ISSUE THREAD

**Issue by Twink1eZzzz** [kangzubin/XMNetworking#16]
Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: application/atom+xml" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x6080002305c0> { URL: http://101.201.81.96:8081/biz-ws-deploy/service/play/play/findPlayHomePage?userId=e549d1e054096f4701540992b516001b } { status code: 200, headers {
    "Content-Type" = "application/atom+xml";
    Date = "Fri, 06 Jan 2017 07:32:00 GMT";
    Server = "Apache-Coyote/1.1";
    "Transfer-Encoding" = Identity;
} }, NSErrorFailingURLKey=http://101.201.81.96:8081/biz-ws-deploy/service/play/play/findPlayHomePage?userId=e549d1e054096f4701540992b516001b, com.alamofire.serialization.response.error.data=<7b226461 7461223a 7b224c69 66654c69 7374223a 5b7b2263 6c617373 69667922 3a223022 2c22636f 6d6d6f64 69747949 64223a22 65353439 64316530 35366439 36303430 30313536 66393665 35323638 30383538 222c2263 6f6d6d6f 64697479 4e616d65 223a22e8 a281e8ae b0e4b8b2 e4b8b2e9 a699efbc 8834e4ba bae5b9b2 e99485e5 a597e9a4 90efbc89 222c2269 6d67223a 22687474 703a2f2f 3130312e 3230312e 38312e39 363a3830 .......

**Comment by kangzubin** [comment]
http://101.201.81.96:8081/biz-ws-deploy/service/play/play/findPlayHomePage?userId=e549d1e054096f4701540992b516001b

在这个接口，你们服务端返回的数据虽然是 JSON 格式，但是声明的 ContentType 却是 `application/atom+xml`，这是不符合标准的，请让你们服务端开发的同学把该接口的 ContentType 改成 `application/json` 或 `text/json` 或 `text/javascript`，详见 `AFJSONResponseSerializer`。
