### ISSUE TITLE
对XM_SAFE_BLOCK的实现有点疑问

### ISSUE THREAD

**Issue by crossPQW** [kangzubin/XMNetworking#18]
想了解一下`XM_SAFE_BLOCK`这个宏是实现什么功能的？还有为什么能实现

**Comment by westke** [comment]
if (blockName) {
        blockName(参数)
}
判断使用者是传了nil还是传了block体，如果传nil，并且不判断就用blockName(参数)回调是会闪退的，又因为里面用了很多block进行回调，写上面的判断不优雅，改用宏了～

**Comment by westke** [comment]
@crossRQW
```
if (blockName) {
     blockName(参数)
}
```
判断使用者是传了nil还是传了block体，如果传nil，并且不判断就用blockName(参数)回调是会闪退的，又因为里面用了很多block进行回调，太多类似的判断不优雅，改用宏了～
