### ISSUE TITLE
text/html没有做处理吗？

### ISSUE THREAD

**Issue by gaoshilei** [kangzubin/XMNetworking#19]
response数据是text/html格式，还要去AFN的AFHTTPResponseSerializer中改acceptableContentTypes，在XMN的XMEngine修改- (AFHTTPSessionManager *)sessionManager中的_sessionManager.responseSerializer.acceptableContentTypes
却无效，这是什么原因？

**Comment by gaoshilei** [comment]
找错了😓，在- (AFJSONResponseSerializer *)afJSONResponseSerializer里面

**Comment by kangzubin** [comment]
您好，你不需要去改源码，`XMRequest` 有个属性 `XMResponseSerializerType` 可以修改响应数据的类型，默认是 `JSON`，如果是 `text/html` 格式，可以设置为 `RAW`，请详细阅读文档或源码说明。
