### ISSUE TITLE
有没有基于afn2.5.3的XMNetworking

### ISSUE THREAD

**Issue by championfu** [kangzubin/XMNetworking#23]
我这边集成海康SDK时，他们的登录静态库使用了afn2.5.3，改不了源码，很是纠结，我尝试去改XM框架，发现问题好多，要改的不只是XMEngine里面的东西，而且，我也没认真研究afn的迁移改动，想问问您，有没有基于老版本的框架，没有的话，能不能给些修改指导意见。万分感谢！！！

**Comment by kangzubin** [comment]
在 `XMNetworking` 中用到的 `AFNetworking` 3.1.0 的代码中，把所有以 "AFxxx" 开头的类都加个前缀，比如 "XMAFxxx"，然后只要把 `XMEngine` 中用到的所有 `AFNetworking` 相关的类都改成以 `XMAFxxx` 开头的类，就可以解决冲突了。

PS: 那个什么海康 SDK，作为一个 SDK，居然直接赤裸裸地用了 `AFNetworking` 这种几乎每个 App 都会的网络库，而不做任何类名修改（如加个前缀等），完全不考虑宿主 App 的感受，我也是醉了，这种 SDK 不用也罢。

**Comment by championfu** [comment]
非常感谢，虽然方法很笨，但还是能成功，xcode不识别大小写，替换的时候剔除小写af眼睛都看炸了，还有的变量是以kAF开头，坑还是蛮多的，修改好了，谢谢啊
