### ISSUE TITLE
光star实在不足以表达激动之情

### ISSUE THREAD

**Issue by beiguancyc** [kangzubin/XMNetworking#3]
一直想自己封装个网络库，不过老是给自己的懒惰找理由。今天看到xm，所有的方法都看了一遍，我想做的，xm全做了。如果能再加上缓存，估计我可以把自己的项目全部都换血用xm了

**Comment by kangzubin** [comment]
谢谢支持，缓存一开始的设计确实是放在网络层，但后面我们把它抽离出去放到业务逻辑层去做了，现在你可以通过 [XMCenter setResponseProcessBlock:...] 方法以 Block 注入的方式为 XMNetworking 实现你自己的缓存逻辑，接下来我们也会持续完善网络缓存相关的功能。
