### ISSUE TITLE
批量请求有没有数量限制

### ISSUE THREAD

**Issue by ilovequanquan** [kangzubin/XMNetworking#4]

**Comment by kangzubin** [comment]
目前批量请求是没有数量限制的。批量请求的使用场景是：发一组业务逻辑上相关，但请求本身是互相独立的网络请求，然后统一在一个回调 Block 里处理这些请求的响应数据。所以不建议一次性发过多的批量请求，不然处理起来可能会有性能上的问题。

**Comment by ilovequanquan** [comment]
好的谢谢啦
