### ISSUE TITLE
数据解析是不是有问题？

### ISSUE THREAD

**Issue by BestKai** [kangzubin/XMNetworking#49]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/8436462/53001965-a1f4e300-3466-11e9-8804-341c93371c1b.png">
这里如果设置kXMResponseSerializerJSON 为什么不用AFJSONResponseSerializer 解析而依然是AFHTTPResponseSerializer。这里解析不出来问题。

**Comment by BestKai** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/8436462/53002360-83431c00-3467-11e9-94cc-86265d80855b.png">
这里设置acceptableContentTypes的地方注释掉的原因是什么？如果注释掉了有些接口返回数据不能解析。

**Comment by kangzubin** [comment]
注释掉的原因是因为：AFJSONResponseSerializer 本身默认支持的 ContentTypes 为 `application/json`、`text/json`、`text/javascript`，上述注释代码是为了兼容服务端返回的 ContentTypes 不规范的问题，JSON 类型的数据对应的 ContentTypes 应为 `application/json`，而不应该为其他类似 `text/html` 或者 `text/plain`，所以注释掉了，建议服务端接口修正 ContentTypes。

**Comment by BestKai** [comment]
> 注释掉的原因是因为：AFJSONResponseSerializer 本身默认支持的 ContentTypes 为 `application/json`、`text/json`、`text/javascript`，上述注释代码是为了兼容服务端返回的 ContentTypes 不规范的问题，JSON 类型的数据对应的 ContentTypes 应为 `application/json`，而不应该为其他类似 `text/html` 或者 `text/plain`，所以注释掉了，建议服务端接口修正 ContentTypes。
明白了，非常感谢
