### ISSUE TITLE
不应允许非标准的 Content-Type

### ISSUE THREAD

**Issue by skyline75489** [kangzubin/XMNetworking#5]
https://github.com/kangzubin/XMNetworking/blob/master/XMNetworking/Core/XMEngine.m#L381

这里放宽了对于 Content-Type 的限制，不知意义何在？如果仅仅是为了好用的话，感觉是没有必要的。

**Comment by kangzubin** [comment]
您说得很对，之前之所以加上 "text/html",  "text/plain" 是因为历史遗留问题很多 Server 端的 API 返回了 JSON 数据但是 Content-Type 却不是标准的 "application/json"，所以这里做了兼容处理；

接下来会考虑让使用者可按需求自定义修改可接收的 Content-Type 类型。
