### ISSUE TITLE
一个M3U8视频本身就需要下载多个 ts切片链接，如何批量下载多个M3U8视频？

### ISSUE THREAD

**Issue by LeeCenY** [kangzubin/XMNetworking#6]

**Comment by LeeCenY** [comment]
http://v1.kokojia.com/video/2016/07/17/40229/video_0.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_1.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_2.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_3.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_4.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_5.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_6.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_7.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_8.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_9.ts
#EXTINF:16.666667,
http://v1.kokojia.com/video/2016/07/17/40229/video_10.ts

**Comment by kangzubin** [comment]
你好，根据你的需求，对于下载一个 M3U8 视频的多个 ts 切片链接，可以通过如下方式发批量请求，然后在 success block 里对结果进行加工处理；

```objc
    [XMCenter sendBatchRequest:^(XMBatchRequest * _Nonnull batchRequest) {

        for (int i = 0; i <= 10; i++) {
            NSString *downloadUrl = [NSString stringWithFormat:@"http://v1.kokojia.com/video/2016/07/17/40229/video_%d.ts", i];
            NSString *savePath = [NSHomeDirectory() stringByAppendingString:@"/Documents/"];
            XMRequest *request = [XMRequest request];
            request.url = downloadUrl;
            request.downloadSavePath = savePath;
            request.requestType = kXMRequestDownload;
            [batchRequest.requestArray addObject:request];
        }
        
    } onSuccess:^(NSArray<id> * _Nonnull responseObjects) {
        NSLog(@"onSuccess: %@", responseObjects);
    } onFailure:^(NSArray<id> * _Nonnull errors) {
        NSLog(@"onFailure: %@", errors);
    } onFinished:^(NSArray<id> * _Nullable responseObjects, NSArray<id> * _Nullable errors) {
        NSLog(@"onFinished");
    }];
```

但是，如果需要同时批量下载多个 M3U8 视频，并且每个视频都有多个 ts 切片链接，这时就会有批量请求里又套批量请求的情况，对于网络层来说，逻辑过于复杂且使用场景不多，所以建议放到业务逻辑层去做，可手动多次调用上述代码去下载不同的包含多个切片的 M3U8 视频。
