### ISSUE TITLE
chainRequest的一个小疑问

### ISSUE THREAD

**Issue by JoakimLiu** [kangzubin/XMNetworking#7]
https://github.com/kangzubin/XMNetworking/blob/master/XMNetworking/Core/XMCenter.m#L295
这里应该是
```objc
[chainRequest onFinishedOneRequest:request response:responseObject error:error];
```
吧？

https://github.com/kangzubin/XMNetworking/blob/master/XMNetworking/Core/XMRequest.m#L219
并且这里暂时也没有用到`request`入参.

**Comment by kangzubin** [comment]
非常感谢指出，之前整理代码时疏忽了，

https://github.com/kangzubin/XMNetworking/blob/master/XMNetworking/Core/XMCenter.m#L295 

这里确实应该是：
```objc
[chainRequest onFinishedOneRequest:request response:responseObject error:error];
```
另外，`XMChainRequest` 中的这个方法保持了与 `XMBatchRequest` 中的方法参数一致，

https://github.com/kangzubin/XMNetworking/blob/master/XMNetworking/Core/XMRequest.m#L219

而且这里暂时也没有用到 request 入参，所以上述的参数传错的 bug 暂时不影响请求结果的正确性。

非常感谢，下一版本会改过来。
