### ISSUE TITLE
请教个问题,我上传大图片,1-3M的,每次上传完,memory就增加了几M

### ISSUE THREAD

**Issue by zhoupIT** [kangzubin/XMNetworking#9]
不知道是为什么

**Comment by zhoupIT** [comment]
试了下,把上传的方法注释掉就不会这样,所以想请教一下

**Comment by kangzubin** [comment]
你好，我这边测试，上传文件结束后，相关的对象都是正常释放掉的，能否把您测试的代码和内存相关的截图发上来看一下吗？

**Comment by zhoupIT** [comment]
XMRequest 是dealloc了,但是memory涨了.请问你的QQ联系方式是?

**Comment by kangzubin** [comment]
我这边再测试一下看是什么原因。如果方便地话，也请把您的测试代码贴上来我看一下。

**Comment by zhoupIT** [comment]
找到大概的原因,貌似是因为我们的上传接口的connection不是keep-alive的,造成的.大神有遇过么?
